default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
- hooks:
  - exclude: ^src/experimaestro/server/data
    id: black
  repo: https://github.com/psf/black
  rev: 25.12.0
- hooks:
  - additional_dependencies:
    - flake8-print
    - flake8-fixme
    id: flake8
  repo: https://github.com/pycqa/flake8
  rev: 7.3.0
- hooks:
  - id: conventional-pre-commit
    stages:
    - commit-msg
  repo: https://github.com/compilerla/conventional-pre-commit
  rev: v4.3.0
