type: trec/adhoc
data:
    - 
        id: ap88 
        description: Associated Press (1988)
        pattern: ^AP88.*$
        handler: trec.documents/sgml
    -
        id: ap89 
        description: Associated Press (1989)
        pattern: ^AP89.*$
        handler: trec.documents/sgml
    -
        id: ap90
        description: Associated Press (1990)
        pattern: ^AP90.*$
        handler: trec.documents/sgml
    -
        id: 1.documents
        description: Data collection used from TREC-1 to TREC-3
        references: [ap88, ap89, doe1, fr88, fr89, wsj87, wsj88, wsj89, wsj90, wsj91, wsj92, ziff1, ziff2]
        handler: trec.documents/collection
    -
        id: 4.adhoc
        description: Data collection used in TREC-4
        references: ap88 ap89 ap90 fr88 sjm1 usp93 wsj90 wsj91 wsj92 ziff2 ziff3
    -
        id: 5.adhoc
        description: Data collection used in TREC-5
        references: ap88 cr1 fr88 fr94 ft1 wsj90 wsj91 wsj92 ziff2
    -
        id: 6.adhoc
        description: Data collection used in TREC-6
        references: cr1 fbis1 fr94 ft1 la8990
    -
        id: 7.adhoc
        description: Data collection used in TREC-7 and TREC-8
        references: fbis1 fr94 ft1 la8990
    -
        id: clueweb09b
        description: The ClueWeb09-B dataset, a subsample from ClueWeb09
        type: warc
        warc-version: 0.18
    -
        id: clueweb12b
        description: The ClueWeb12-B dataset, a subsample from ClueWeb12
        type: warc
        warc-version: 0.18
   
    # --- TREC 1 
   
    -
        id: "1.topics"
        description: "TREC 1 topics"
        handler: trec.adhoc/topics
        properties:
            parts: [desc]
        download:
            handler: single/file
            url: "http://trec.nist.gov/data/topics_eng/topics.51-100.gz"
            replace:
                pattern: "Number:(\\s+)0" 
                replace: "Number: \\1"
    -
        id: "1.qrels"
        description: "TREC 1 relevance assessments"
        handler: trec.adhoc/assesments
        download:
            handler: single/archive
            url: "http://trec.nist.gov/data/qrels_eng/qrels.51-100.disk1.disk2.parts1-5.tar.gz"

    -
        id: ["1", "1992.adhoc"]
        description: "Ad-hoc task of TREC 1 (1992)"
        handler: trec.adhoc/task
        topics: !dataset ".1.topics"
        documents: !dataset ".1.documents"


    # --- TREC 2
    # --- TREC 3
    # --- TREC 4
    # --- TREC 5

    -
        id: "5.topics"
        description: "TREC 5 topics"
        handler: trec.adhoc/topics
        download:
            handler: single/file
            url: "http://trec.nist.gov/data/topics_eng/topics.251-300.gz"

    # --- TREC 6
    # --- TREC 7
    # --- TREC 8
    


    -
        id: ["2.adhoc", "1993.adhoc"]
        description: "Ad-hoc task of TREC 2 (1993)"
        documents: "trec.1.adhoc"
        topics:
            properties:
                parts: [desc]
            url: "http://trec.nist.gov/data/topics_eng/topics.101-150.gz"
        qrels:              
            url: "http://trec.nist.gov/data/qrels_eng/qrels.101-150.disk1.disk2.parts1-5.tar.gz"
            type: "tar.gz#gz"
    -
        id: ["trec.3.adhoc", "1994.adhoc"]
        description: "Ad-hoc task of TREC 3 (1994)"
        documents: "trec.1.adhoc"
        topics:
            properties:
                parts: [desc]
            url: "http://trec.nist.gov/data/topics_eng/topics.151-200.gz"
        qrels:              
            url: "http://trec.nist.gov/data/qrels_eng/qrels.151-200.201-250.disks1-3.all.tar.gz"
            type: "tar.gz#gz"
    -
        id: ["trec.4.adhoc", "1995.adhoc"]
        description: "Ad-hoc task of TREC 4 (1995)"
        documents: "trec.4.adhoc"
        topics:
            properties:
                parts: [desc]
            url: "http://trec.nist.gov/data/topics_eng/topics.201-250.gz"
        qrels:              
            url: "http://trec.nist.gov/data/qrels_eng/qrels.251-300.parts1-5.tar.gz"
            type: "tar.gz#gz"
