version: 2
jobs:
  build:
    docker:
    - image: quay.io/pypa/manylinux2010_x86_64
    steps:
    - checkout
    - run:
        name: Setup basic environment
        command: |
          echo "export PATH=/opt/python/cp37-cp37m/bin:/opt/python/cp38-cp38m/bin:$PATH" >> $BASH_ENV
          /opt/python/cp37-cp37m/bin/pip install tox twine
    - restore_cache:
        key: v1-dependency-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
    - run:
        name: install python dependencies
        command: |
          tox --notest -e ALL
    - save_cache:
        key: v1-dependency-cache-{{ checksum "requirements.txt" }}-{{ checksum "tox.ini" }}
        paths:
        - .tox/py37
        - .tox/py38
    - run:
        name: run tests
        command: |
          tox -e ALL

    - store_test_results:
        path: test-reports

    - run:
        name: Upload
        command: |
          if [ "v$(python setup.py --version)" = "$CIRCLE_TAG" ]; then
            echo "Uploading using twine"
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
            python setup.py bdist_wheel
            twine upload dist/datamaestro-*-none-any.whl
          fi
workflows:
  build_and_deploy:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
        context: PyPI
  version: 2
